-- V6__add_klass_public_slug.sql
--
-- Adds a stable, opaque, public identifier to the klass table — the
-- path segment in parent-facing registration URLs (e.g.
-- https://app.example.com/r/Bk7mP2x9qL).
--
-- The slug is 10 characters of base62 ([A-Za-z0-9]), generated by
-- application code (SlugGenerator) at class creation time. This
-- migration only declares the column and its constraints; no backfill
-- is needed because there are no production deployments and dev
-- databases are recreated freely.
--
-- Why a slug rather than reusing klass.id (UUID):
--   - The UUID is an internal identifier; the slug decouples external
--     URLs from internal storage choices.
--   - UUIDv7 embeds a creation timestamp; the slug is genuinely opaque.
--   - 10-char slugs survive a copy-paste round-trip through WhatsApp;
--     36-char UUIDs with hyphens often do not.
--   - Possessing the slug IS the authorization to register a child to
--     that class. Unguessability matters: 62^10 ≈ 8.4 × 10^17 values.

ALTER TABLE klass
    ADD COLUMN public_slug VARCHAR(10) NOT NULL;

ALTER TABLE klass
    ADD CONSTRAINT uq_klass_public_slug UNIQUE (public_slug);